name: Generate Resume PDF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF from HTML
        run: |
          mkdir -p assets
          wkhtmltopdf index.html assets/resume.pdf

      - name: Commit PDF back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add assets/resume.pdf
          git commit -m "Update resume.pdf" || echo "No changes to commit"
          git push
