name: Generate Resume PDF

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install wkhtmltopdf
        run: sudo apt-get update && sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF from GitHub Pages
        run: |
          mkdir -p output
          # Replace with your actual Pages URL
          wkhtmltopdf --enable-local-file-access \
            https://joedunn123456789.github.io/CSS-Resume/ \
            output/resume.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: output/resume.pdf
